### ISSUE TITLE
Error: Undefined function 'fieldnames' for input arguments of type 'cell'.

### ISSUE THREAD

**Issue by craigim** [joe-of-all-trades/xml2struct#1]
In lines 79-80:

``` matlab
textfields = fieldnames(text);
if(~isempty(fieldnames(textfields)))
```

I get the error listed in the title because `text` is a struct and so `fieldnames` returns a cellstr. I believe line 80 should instead be:

``` matlab
if ~isempty(textfields)
```

When I make the change, the program runs as expected.

**Comment by joe-of-all-trades** [comment]
@craigim Thanks for raising this issue. It's left over from my previous change on the code.
